// Configuración por defecto en caso de que falle la carga desde el backend
export const defaultConfig = {
  userId: 4,
  numPlusOne: 1,
  guestViewColumns: {
    id: true,
    fullName: true,
    email: true,
    phone: true,
    validated: true,
    menu: false,
    allergy: false,
    needs_hotel: false,
    needs_transport: false,
    disability: false,
    observations: true,
    accommodation_plan: false,
    isMainGuest: true,
    tags: true,
  },
  guestViewFilters: {
    full_name: true,
    phone: true,
    menu: false,
    allergy: false,
    needs_hotel: false,
    needs_transport: false,
    validated: true,
    tags: true,
    accommodation_plan: false,
  },
  guestFormFields: {
    first_name: true,
    last_name: true,
    phone: true,
    email: true,
    needs_transport: false,
    needs_hotel: false,
    disability: false,
    menu: false,
    allergy: false,
    observations: true,
    accommodation_plan: false,
    tags: true,
    plus_ones: true,
    plus_one_first_name: true,
    plus_one_last_name: true,
    plus_one_menu: false,
    plus_one_allergy: false,
    plus_one_disability: false,
  },
  profileViewFields: {
    bankAccount: false,
    giftList: false,
  },
};

export default defaultConfig;
