// Configuración por defecto en caso de que falle la carga desde el backend
export const defaultConfig = {
  userId: 1,
  numPlusOne: 1,
  guestViewColumns: {
    id: true,
    fullName: true,
    email: true,
    phone: true,
    validated: true,
    menu: true,
    allergy: true,
    needs_hotel: true,
    needs_transport: true,
    needs_transport_back: true,
    disability: true,
    observations: true,
    accommodation_plan: true,
    isMainGuest: true,
    tags: true,
  },
  guestViewFilters: {
    full_name: true,
    phone: true,
    menu: true,
    allergy: true,
    needs_hotel: true,
    needs_transport: true,
    needs_transport_back: true,
    validated: true,
    tags: true,
    accommodation_plan: true,
  },
  guestFormFields: {
    first_name: true,
    last_name: true,
    phone: true,
    email: true,
    needs_transport: true,
    needs_transport_back: true,
    needs_hotel: true,
    disability: true,
    menu: true,
    allergy: true,
    observations: true,
    accommodation_plan: true,
    tags: true,
    plus_ones: true,
    plus_one_first_name: true,
    plus_one_last_name: true,
    plus_one_menu: true,
    plus_one_allergy: true,
    plus_one_disability: true,
  },
  profileViewFields: {
    bankAccount: true,
    giftList: true,
  },
};

export default defaultConfig;
